### PR TITLE
Added an example showcasing animation with keyframe

### PR DESCRIPTION
**Pull request by PSteinhaus**
Based on the discussion in #910 I finally made an example showcasing both tween and frame-by-frame animations using keyframe.

It... works, but there's some code duplication, that I'd really like to get rid off.
But after fiddling with generics for some time I now think the only option would be to use macros to do that, but I'm unsure as to whether we'd want to do that, since we probably don't want to force new (Rust) users to read macro code in order to understand the example.

But maybe I'm missing something.

### CODE REVIEW

**Comment by PSteinhaus** [comment]
Oh, and it seems I also need a workaround for all these enum variants never being "officially" constructed anywhere...

**Comment by PSteinhaus** [comment]
Ok, now that I was able to get rid of the code duplication I'm satisfied with the example.
It's still somewhat long, but it's also a bit shorter than examples like `shadow.rs` or `snake.rs`, so I think it's alright.

**Comment by nobbele** [comment]
what's with the transmutes, doesn't `my_enum as i32` work if you just assign a number to the variants

**Comment by PSteinhaus** [comment]
> what's with the transmutes, doesn't `my_enum as i32` work if you just assign a number to the variants

It does, but the other way around doesn't work. So I thought it's a bit more explicit to use transmute both ways.
I could also change it to `as`` and refactor the transmute into a `From<i32>` implementation, for both enums. Or we could use the `num_derive` and `num_traits` crates.

**Comment by nobbele** [comment]
adding num_traits and num_derive to dev dependencies should be fine

**Comment by PSteinhaus** [comment]
Ok, done.

**Review by nobbele — APPROVED** [review]

**Pull request merged**
