### PR TITLE
[fix #579] Panic on `Option::unwrap()`

### LINKED ISSUE #579: Panic on `Option::unwrap()`
I can't seem to get GGEZ working at all. It always panics on an unwrap - but otherwise gives no useful errors. 

For instance, running the `01_super_simple` example:

```
jeroen@archtop ~/Documents/code/ggez (master) $ RUST_BACKTRACE=1 cargo run --example 01_super_simple
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/examples/01_super_simple`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::panicking::panic
             at src/libcore/panicking.rs:59
   9: <core::option::Option<T>>::unwrap
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/macros.rs:20
  10: winit::platform::platform::wayland::window::Window::get_current_monitor
             at /home/jeroen/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/wayland/window.rs:267
  11: winit::platform::platform::Window::get_current_monitor
             at /home/jeroen/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/mod.rs:348
  12: winit::window::<impl winit::Window>::get_current_monitor
             at /home/jeroen/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/window.rs:406
  13: <ggez::graphics::context::GraphicsContextGeneric<B>>::set_window_mode
             at src/graphics/context.rs:536
  14: <ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>>::new
             at src/graphics/context.rs:315
  15: ggez::context::Context::from_conf
             at src/context.rs:74
  16: ggez::context::ContextBuilder::build
             at src/context.rs:261
  17: _01_super_simple::main
             at examples/01_super_simple.rs:47
  18: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  21: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  22: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
```

### PR DESCRIPTION
**Pull request by karol-szuster**
I would rather consider this to be a temporary workaround until this issue gets properly fixed in winit. If you would rather wait for a proper fix in winit than fell free to drop this PR.

### CODE REVIEW

**Comment by icefoxen** [comment]
Thanks, I hate it.  :grin:  The problem itself, that is, not your code.

I'll merge this into `devel` but I'm going to want to add some robustness to it, instead of just doing nothing when something terrible happens.

**Comment by karol-szuster** [comment]
Yes, I think I should add `panic` there instead of silently doing nothing. I belive that `get_available_monitors` shouldn't return empty list unless you don't have any monitor attached.
I suppose that no one will try to run a game on a headless machine but in that case `panic`-ing seems to be only viable option.
I will update this PR if you don't have any objections,

**Comment by icefoxen** [comment]
Go right ahead, sure!

**Comment by karol-szuster** [comment]
Just to let you know, I've updated PR.

**Comment by icefoxen** [comment]
Thanks, belatedly.  :heart:

**Pull request merged**
