### PR TITLE
fixed drawing transformation matrix

### PR DESCRIPTION
**Pull request by PSteinhaus**
This pull request fixes how the transformation matrix is calculated, making offset work as intended.
For more details and examples of the problematic behavior see #879.

### CODE REVIEW

**Comment by icefoxen** [comment]
Thank you!  I'll check this out and try to make sure it doesn't break anything else.

**Comment by PSteinhaus** [comment]
Testing it I found out that it breaks the spritebatch example a little.
It's still working, but it looks a little differently now. This is probably because the offset of a spritebatch currently works differently (being based not on a 1x1 size, but the size of the drawing surface that is), which amplyfies the bug which gets fixed in this PR. Therefore any countermeasures applied to the example to make it look nice are now no longer working as expected.

**Comment by PSteinhaus** [comment]
While I was at it I also fixed #888 and #736. I hope that's ok.

Fixing #736 was a bit painful though. Now, when you use an offset with a SpriteBatch you'll have to pay a heavy performance cost, because SpriteBatch::dimensions needs to be calculated in every frame in this case. I made sure to include a check whether there actually is an offset, to safe most users from this cost.

**Comment by icefoxen** [comment]
I'm still crossing my fingers merging this, but I can't find anything wrong with it yet...

**Pull request merged**
