### PR TITLE
Audio timing API

### PR DESCRIPTION
**Pull request by mbillingr**
Implements audio timing as discussed in #353. This feature was missing in #437 but was easy enough to add.

I have set the default query interval to 100ms. This should add little overhead for users that don't need this feature (10 `Arc` derefs and atomic increments per second and sound). The interval can be adjusted to get higher precision or better performance.

cc @cessen

### CODE REVIEW

**Comment by icefoxen** [comment]
Does an `AtomicUsize` really need to be `Arc`'ed?  Guess it depends on whether we want a `Source` to be an object, or a handle to an object.  I was leaning towards the former, especially given `Source` doesn't even impl `Clone`...

**Comment by mbillingr** [comment]
I'd be happy to avoid the `Arc`, but I do not know how to give both the audio thread and the `Source` object access to the same `AtomicUsize` without running into lifetime issues...

The problem here is that we do not know who lives longer audio thread or `Source`. Shared ownership of the counter is the only solution I could think of.

**Comment by icefoxen** [comment]
Yep, my bad, I was `AtomicUsize` avoids a `RefCell` or such, not an `Arc`.  Derp.

Might it be easier though to have a `Source` store the time that it started playing?

Sorry for taking so long to get to this.

**Comment by mbillingr** [comment]
I don't see how storing the start time could help here. As far I understood #353  the point was not to depend on the system clock because it drifts compared to the sound cards sample rate.

Maybe it's not worth to implement this very specific functionality. Could it be an alternative to expose Rodio structures through `Source` (not sure if that's easily possible) so that downstream users can implement such functionality if they need it?

**Comment by icefoxen** [comment]
> As far I understood #353 the point was not to depend on the system clock because it drifts compared to the sound cards sample rate.

Derp, my bad then.  Thanks.

> Maybe it's not worth to implement this very specific functionality. 

Eeeeh.  This system seems to do the Right Thing in that case, and doesn't add much extra complexity or overhead, and timing-exact audio is both important (for things like rhythm games), and hard to do well (afaik there's actually no possible way to make it work perfectly on Android, though that may be out of date now).  We'll roll with it by now and see how it goes.

Thank you again!

**Pull request merged**
