### PR TITLE
Logging feature.

### PR DESCRIPTION
**Pull request by Ratysz**
Rewrote how `ggez` handles internal logging, and implemented a new feature: `use-log-crate`; example included.

Now, by default, `ggez` will format internal log messages as `[target][LEVEL] message`, close to how a simple frontend of [`log`](https://docs.rs/log/) crate would do it.

When compiled with `--features "use-log-crate"`, internal logging will instead use macros from [`log`](https://docs.rs/log/) crate.

From end user (read: executable) perspective, it's entirely opt-in, as demonstrated by all examples (save for new "logging" example, which shows how to actually opt-in).

**Details**

This is achieved via a set of new macros, like `ggez_info!` or `ggez_error!`, that closely mimic equivalent macros from `log` crate (`info!`, `error!`, etc).

Without `use-log-crate` feature these compile down to print aforementioned `[target][LEVEL] message` line; with the feature the macros compile down to their direct equivalents from `log` crate.

As far as I know, there is no runtime overhead - when the feature is disabled, at least. With the feature, it most likely depends on chosen logging frontend.

`ggez`-depending libraries can use these new macros as well, preserving the opt-in behavior for their dependant executables.

Examples and tests were not touched, so grand total of actual changed lines is 4.

The random diffs are from rustfmt.

**Open questions**

Names. Feature itself (currently `use-log-crate`), macros (currently `ggez_X!`, with *X* being all the macros from `log` crate).

Default. Should this feature be enabled by default? (currently no)

Docs. I've put in a lot of hard links there, couldn't be bothered to learn if there's a better way (yet).

Alternative approach. It might be simpler (to understand and maintain) to embrace `log` crate internally, and provide an internal fallback logger frontend that just `println!`s the records - not entirely sure how overhead-free that would be.

That should be all the info needed to start a discussion; I'll comment if I remember anything else. Questions, edits, reviews, comments, etc are all welcome, of course.

### CODE REVIEW

**Comment by icefoxen** [comment]
Well this is interesting.  I have no idea what to think of this.

It appears that just using the `log` crate to do logging by default does nothing, and allow users to specify a logging backend that will actually output messages.  For a library, that seems like the desired behavior.

I'm going to have to play with this more.

**Comment by Ratysz** [comment]
... oh. For some reason, I assumed you knew what `log` crate does and how it does it, and [this comment](https://github.com/ggez/ggez/issues/294#issuecomment-371861897) implied that wasn't going to work for `ggez`. I blame the flu.

In light of that, my suggested alternative approach might be the way to go - I'll tinker with that within the week, while discussion is (hopefully) happening.

**Comment by icefoxen** [comment]
Derp.  XD  I know what `log` does but not that much about how it does it.  Sorry.  I haven't thought about this problem very hard lately.  This PR, I confess, makes it a little bit more clear that using something like `log` may be easier and less problematic than I expected.

Also I feel that logging is a little orthogonal to that particular issue, since I was thinking of that as an API problem, not as a communicating-information-to-humans problem.  The desired behavior in that issue is "the program can see something went wrong, then decide to keep going in a degraded state"; informing the user that something is wrong doesn't do that, so I wasn't thinking about that angle.

**Comment by Ratysz** [comment]
"Alternative approach" over at #310; leaving this open until we pick a solution.

**Comment by icefoxen** [comment]
:+1: 

I'll see if I can get time to play with both of these and see how they stack up against each other.

**Comment by Ratysz** [comment]
Closing in favor of #331

**Pull request closed without merging**
