### PR TITLE
Start for MSAA

### PR DESCRIPTION
**Pull request by termhn**
Addressing #152 Began trying to implement MSAA. This should in theory work as it is now, but gfx_window_sdl needs to be patched to allow the surface to be multi-sampling aware. Working on that now but it's not working yet for some reason. Need to run it through renderdoc or apitrace or something to inspect closer.

### CODE REVIEW

**Comment by icefoxen** [comment]
Oh cripes more?

**Comment by icefoxen** [comment]
As long as you're rewriting the ggez graphics system anyway, do you have any clever ideas for making it possible for users to provide custom shaders? Think about it.

**Comment by termhn** [comment]
Heh, I've been thinking about it. I need to look more into how gfx actually builds shader programs and stuff. I like the way LOVE does it API wise a fair amount, but I haven't really looked into how that would look like with gfx at all.

**Comment by termhn** [comment]
Alright, it actually did and does work, I just didn't notice because I had the number of samples relatively low. I'm dumb.

It's now defined in the WindowMode with a default of 16 samples, but it's not yet editable after the window has been created.

Everything looks so niiiiiiiiiiiiice with 16 samples *_*

**Pull request merged**
