### PR TITLE
`conf` module improvements

### PR DESCRIPTION
**Pull request by Ratysz**
This is a running PR to track changes to `conf` module, mentioned in #391 [(this comment)](https://github.com/ggez/ggez/issues/391#issuecomment-396045308).

### CODE REVIEW

**Comment by Ratysz** [comment]
Ran into something unexpected: apparently, `toml` crate [does not support](https://docs.rs/toml/0.4.6/toml/ser/enum.Error.html) serializing enums, tuples, and tuple structs. Which is weird, considering that `FullscreenType` is an enum, and it has no problem de/serializing it's `::Off` variant. It does complain about any other variant, though.

**Comment by icefoxen** [comment]
Part of the problem is basically that rust has no way of distinguishing "c-like" enums which have no additional data attached from enums where some variants include tuples or structs. This makes life hard for some serializers.

**Comment by Ratysz** [comment]
Yes, I sort of understand the why of it. I'm putting together a workaround that lets us keep the tuples and everything (it involves some manual `serde` sorcery).

**Comment by icefoxen** [comment]
An easier option might be to just have accessor and builder methods to manage the tuples, or just drop them altogether?  :man_shrugging:

**Comment by Ratysz** [comment]
This should be pretty much it. There are a few more settings I decided are not worth exposing: `gl_debug_flag`, `gl_robustness`, `stereoscopy`. First two aren't useful in context of facaded GL, the last one is too niche.

**Comment by icefoxen** [comment]
I've been putting off because I expected it might be the case, but...  I like the changes in general but I hate the TOML it results in:

```toml
[window_mode]
maximized = false
hidden = false
borderless = false
always_on_top = false

[window_mode.dimensions]
option = "Some"
width = 800
height = 600

[window_mode.min_dimensions]
option = "None"

[window_mode.max_dimensions]
option = "None"

[window_mode.fullscreen_type]
type = "Off"

[window_setup]
title = "An easy, good game"
icon = ""
resizable = false
transparent = false
use_compatibility_profile = false
vsync = true
samples = "One"
srgb = false

[backend]
type = "OpenGL"
major = 3
minor = 2
```

I don't really consider the options to be hand-editable... if I want to change `max_dimensions` to be something, what am I supposed to do?  Change `option` to `Some`, obviously, and then....?  If I want to change `fullscreen_type` to be `Desktop` and have to put in a `MonitorId`, then what do I do there?

There has to be a way to make it more TOML-y...

**Comment by Ratysz** [comment]
Now that you mention it, yeah, that is pretty bad. Somehow it never occurred to me to *really* look at it from user side - I was operating from assumption that most folks will work with `Conf` from Rust side, which is just not true. And, I was (still am) pretty angry at TOML's whitespace dependence.

I'll try and fix this, probably using a full intermediate struct - so that both TOML side and Rust side make sense in their own context.

**Comment by Ratysz** [comment]
Done. Structs are largely unchanged since last time, but TOML now looks like this:
```toml
[window_mode]
always_on_top = true

[window_mode.dimensions]
width = 640
height = 480

[window_mode.min_dimensions]
width = 640
height = 480

[window_mode.fullscreen]
type = "Desktop"
monitor = 1

[window_setup]
title = "Testing, testing, one, two"
samples = "Four"
vsync = false

[backend]
type = "OpenGL"
version_major = 4
version_minor = 6
```
Not all fields are present because I went ahead made everything optional at TOML side. If a field is not defined, it will initialize with default value. If this is something we *don't* want, it's easy enough to change back.

Wrote a fair bit of examples/doctests - they're easy to maintain, since compiler itself will point out if something is wrong during testing. Can be explored rendered [here](http://ratysz.github.io/ggez/conf/index.html).

**Comment by Terkwood** [comment]
Nice improvement!

**Comment by icefoxen** [comment]
> If this is something we don't want, it's easy enough to change back.

I'd prefer having all fields have explicit values instead of "field is absent" meaning "use default value".  Makes it easier for a user to look at the config file and see everything that's going on, and it protects against defaults potentially changing.

**Comment by icefoxen** [comment]
@Ratysz Some rather belated feedback...

 * Always prefer implementing `From` rather than `Into` where possible.
 * Make everything as simple as possible, but no simpler.  :-)  For example, storing `MonitorId` for `FullscreenType` instead of just using `Current` everywhere is a lot of complexity for quite little gain... I don't recall many games letting you select which monitor you want to display on.  Trying to shove `Option` types into TOML which isn't designed for them is quite a lot of complexity for little gain.  

Upon consideration I'm going to have to sit and think about this more, and ponder whether 600 lines of code for ultimately cosmetic improvements is really worth it.    There's *got* to be a better way... and maybe it's as simple as "use something more powerful than TOML".  [ron](https://github.com/ron-rs/ron), perhaps?

**Comment by Ratysz** [comment]
> I'd prefer having all fields have explicit values instead of "field is absent" meaning "use default value".

My reasoning was, we're not actually generating the `conf.toml` file, unless user app does it itself, and the only way for users to know which fields they need is to look in documentation anyway (barring trial and error). Now, not saving default fields with `Conf::to_toml_file()` likely *is* a bad call.

> [...] protects against defaults potentially changing.

Yes, I haven't even considered that.

> Always prefer implementing `From` rather than `Into` where possible.

I was led to believe these are completely equivalent, as one always implicitly implements the other. Or is it for clarity?

>  [...] using `Current` everywhere [...]

Simplest solutions are the best... There's a long line of thought that can be summed up as me latching onto supporting as much of `winit` functionality as possible. This will also simplify a couple of points from the integration tracking issue.

> [...] quite a lot of complexity [...]

I'd argue it's more verbosity, rather than complexity. The `custom_ser_de` submodule (the 600 lines) is quite possibly over 1/3 whitespace, and the rest is hand-rolling what `#[serde(bound(...))]` does - because it requires the specified types to be `pub`, thus visible in API.

> [...] "use something more powerful than TOML".

That would allow using `serde` derives as-is, and completely throwing away `custom_ser_de` submodule.

I knew soon after I saw `toml` crate error on my freshly-refactored types that I was asking of it something that it wasn't meant to do. Unfortunately (?), I found ways around those limitations before resigning and reconsidering; not the first time I got carried away 😄 

I'll see if I can pick this apart and create a smaller set of changes; mostly docs.

**Pull request merged**
