### PR TITLE
Quit Event Handler: Add to Keyboard Event & Doc Updates

### PR DESCRIPTION
**Pull request by ducharmemp**
This closes issue #602

### CODE REVIEW

**Comment by ducharmemp** [comment]
Well I messed up the PR... whoops. Reopening once I figure out my issues.

**Comment by icefoxen** [comment]
Yeah I've been a little sloppy about devel vs. master recently and need to tighten that up.  Sorry about that.  For now, if your stuff is based off master, make your PR to master.

**Comment by ducharmemp** [comment]
So what's strange is that on my machine, the cargo test --headless passes. I'll see if I can figure out what's going on here.

**Comment by ducharmemp** [comment]
@icefoxen any ideas on this one? I just took a look and had no idea. Maybe master is unstable under some release version? I know clippy was complaining about image vs ::image

**Comment by icefoxen** [comment]
Sorry for letting this sit forever.  XD  I'm a little skeptical of the interactions between `quit()` and the quit event handler still, I want to sit down and sort that out better at some point.  I'm not sure this PR is correct and need to think about it.

**Comment by icefoxen** [comment]
This is welcome but insufficient, making this work right is going to have to involve lots of weird changes to the event loop stuff anyway.  :-/  See https://github.com/ggez/ggez/issues/602#issuecomment-485869847

**Comment by icefoxen** [comment]
...I did update the docs though, see d5a33c3

**Comment by ducharmemp** [comment]
It might ultimately be more prudent to just have a well documented side
effect than try to solve all of the issues you outlined. Honestly I got the
flu around the time of this pull request and then fell off of the project
that I was working on, so I let this sit a bit longer than I should have.

**Comment by icefoxen** [comment]
Yeah, it definitely might. I do want to play with it a bit more myself. Hope you feel better!

**Pull request closed without merging**
