### PR TITLE
Fix both an image memory leak and text memory leak. Prepare for 0.9.2

### PR DESCRIPTION
**Pull request by Vixeliz**
Hopefully fixes all the known memory leak's properly now. Testing is appreciated

### CODE REVIEW

**Comment by Vixeliz** [comment]
Fyi thanks to TrulyFalse(One of the main authors of the wgpu rewrite) on discord for help with both of these.

**Review by nobbele — APPROVED** [review]

**Comment by nox** [comment]
Tbh this increased minimum Rust version, using `Option::is_ok_and`

**Comment by Vixeliz** [comment]
@nox we target the latest stable release of rust. Sometimes it may compile on earlier versions but that is the target version.

**Comment by nox** [comment]
The readme says

> ggez requires rustc >= 1.42 and is distributed on crates.io.

So you may want to remove that claim.

**Pull request merged**
