### PR TITLE
Get examples to compile and run on macOS.

### PR DESCRIPTION
**Pull request by seivan**
By making `game_pad` optional.

### CODE REVIEW

**Comment by Ratysz** [comment]
I think this would make more sense as a feature gate, if anything.

**Comment by icefoxen** [comment]
I don't disagree but I *really* don't want to load ggez down with feature gates.  They're convenient for a programmer but really inconvenient for an end-user who just has a fixed binary.

How I *want* to do this is make trait objects for each `Context` type and then be able to have, for example, `impl GamepadContext for GilrsContext` and `impl GamepadContext for NullGamepadContext` and just have them able to be chosen/switched at runtime, without needing `Option`'s everywhere.  I think there's a discussion for this somewhere in the issues but I can't find it right now.  It also might not be feasible at all, unfortunately, but I want to try.

**Comment by seivan** [comment]
I am mostly just interesting to get it to run without crashing - any approach to this works for me - but as of now the dev branch doesn't run on macOS.

**Comment by Ratysz** [comment]
Hence "if anything" - I saw #480 and it does seem like the way to go; hopefully, it is indeed feasible.

Could be worthwhile, however, to use a temporary solution (be it `Option`, feature, or plain removal of the dependency) in case of this issue holding up next release.

**Comment by icefoxen** [comment]
Ah, #480, that was it.  Yeah, this will definitely get merged in one way or another soon; I don't intend for this to hold up at least a pre-release, and `GamepadContext` is a good test case to try different strategies.

**Comment by icefoxen** [comment]
Superceded by #487

**Pull request closed without merging**
