### PR TITLE
Send instance transform as matrices encoded in column vectors

### PR DESCRIPTION
**Pull request by termhn**
Last piece of #145. It works, but I haven't done any testing to see if there's any impact on performance. The code definitely is cleaner though, especially in the vertex shader.

### CODE REVIEW

**Comment by icefoxen** [comment]
Any particular reason you're splitting them into separate vec4's instead of just a mat4?

**Comment by icefoxen** [comment]
Also we should do some performance testing just to see what it looks like.  We need a cool particle system demo anyway...  Hmmm.

**Comment by termhn** [comment]
Instance Buffers don't support mat4's in gfx, only vectors.

**Comment by icefoxen** [comment]
per kvark this is a limitation of the GPU hardware, which I'd just never bumped into before.

**Comment by icefoxen** [comment]
Is this ready to merge?  I never know if one of your PR's is good to go or still WIP...

**Comment by termhn** [comment]
Sorry I should be more clear about that haha, but yeah I think this is ready to merge

**Pull request merged**
