### PR TITLE
Lower limits

### PR DESCRIPTION
**Pull request by nobbele**

### CODE REVIEW

**Comment by PSteinhaus** [comment]
Looks good. Haven't done any testing yet though.
Loosing that bind group seems to simplify things quite nicely additionally to satisfying the lower limits.

**Comment by nobbele** [comment]
I want to see if it fixes #1074 but I don't have anything to test it on

**Comment by nobbele** [comment]
Had my friend test it (OpenGL 3.3) and it doesn't fix it

**Comment by snyball** [comment]
@nobbele Tested this on an Ivy Bridge Intel HD 4000 machine, on my end it's not to do with the limits, it simply isn't finding any adapters at all on the older device. You could have your friend test this too to confirm:

```diff
diff --git a/src/graphics/context.rs b/src/graphics/context.rs
index adc516e..983db62 100644
--- a/src/graphics/context.rs
+++ b/src/graphics/context.rs
@@ -136,6 +136,12 @@ impl GraphicsContext {
         let window = window_builder.build(event_loop)?;
         let surface = unsafe { instance.create_surface(&window) };

+        let adapters = instance.enumerate_adapters(wgpu::Backends::all()).map(|a| {
+            (a.get_info(), a.limits())
+        }).collect::<Vec<_>>();
+        println!("Adapters:");
+        dbg!(adapters);
+
         let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
             power_preference: wgpu::PowerPreference::HighPerformance,
             force_fallback_adapter: false,
```

**Comment by PSteinhaus** [comment]
When I run the bunnymark example and go past 10000 bunnies the program crashes with this:
```
C:/Users/jetti/.cargo/bin/cargo.exe run --color=always --package ggez --example bunnymark
    Finished dev [unoptimized + debuginfo] target(s) in 2.36s
     Running `target\debug\examples\bunnymark.exe`
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
    buffer binding 0 range 1056000 exceeds `max_*_buffer_binding_size` limit 960000

', C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:2391:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: wgpu::backend::direct::default_error_handler
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:2391
   3: core::ops::function::Fn::call<void (*)(enum$<wgpu::Error>),tuple$<enum$<wgpu::Error> > >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:77
   4: alloc::boxed::impl$46::call<tuple$<enum$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler<assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\alloc\src\boxed.rs:1965
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:2377
   6: wgpu::backend::direct::Context::handle_error<enum$<wgpu_core::binding_model::CreateBindGroupError> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:261
   7: wgpu::backend::direct::impl$3::device_create_bind_group
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:1286
   8: wgpu::Device::create_bind_group
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\lib.rs:2086
   9: ggez::graphics::instance::InstanceArray::new_wgpu
             at .\src\graphics\instance.rs:112
  10: ggez::graphics::instance::InstanceArray::flush_wgpu
             at .\src\graphics\instance.rs:198
  11: ggez::graphics::instance::impl$1::draw<ggez::graphics::draw::DrawParam>
             at .\src\graphics\instance.rs:291
  12: ggez::graphics::canvas::Canvas::draw<ggez::graphics::instance::InstanceArray,ggez::graphics::draw::DrawParam>
             at .\src\graphics\canvas.rs:347
  13: bunnymark::impl$2::draw
             at .\examples\bunnymark.rs:127
  14: ggez::event::run::closure$0<bunnymark::GameState,enum$<ggez::error::GameError> >
             at .\src\event.rs:530
  15: winit::platform_impl::platform::event_loop::impl$2::run_return::closure$0<tuple$<>,ggez::event::run::closure_env$0<bunnymark::GameState,enum$<ggez::error::GameError> > >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:206
  16: alloc::boxed::impl$45::call_mut<tuple$<enum$<winit::event::Event<tuple$<> > >,ref_mut$<enum$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum$<winit::event::Event<tuple$<> > >,ref_mut$<enum$<winit::event_loop::ControlFlow> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\alloc\src\boxed.rs:1958
  17: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<tuple$<> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:245
  18: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\panic\unwind_safe.rs:271
  19: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\panicking.rs:492
  20: hashbrown::raw::alloc::inner::do_alloc<alloc::alloc::Global>
  21: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > > >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\panicking.rs:456
  22: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\panic.rs:137
  23: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:152
  24: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::call_event_handler<tuple$<> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:239
  25: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::move_state_to<tuple$<> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:341
  26: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::main_events_cleared<tuple$<> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:227
  27: winit::platform_impl::platform::event_loop::flush_paint_messages<tuple$<> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:726
  28: winit::platform_impl::platform::event_loop::thread_event_target_callback::closure$0<tuple$<> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:2091
  29: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> >,tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
  30: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> > >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\panic\unwind_safe.rs:271
  31: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> > >,isize>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\panicking.rs:492
  32: hashbrown::raw::alloc::inner::do_alloc<alloc::alloc::Global>
  33: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> > > >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\panicking.rs:456
  34: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> > >,isize>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\panic.rs:137
  35: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> > >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:152
  36: winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple$<> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:2271
  37: CallWindowProcW
  38: EnumChildWindows
  39: IsIconic
  40: KiUserCallbackDispatcher
  41: NtUserDispatchMessage
  42: DispatchMessageW
  43: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run_return<tuple$<>,ggez::event::run::closure_env$0<bunnymark::GameState,enum$<ggez::error::GameError> > >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:221
  44: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run<tuple$<>,ggez::event::run::closure_env$0<bunnymark::GameState,enum$<ggez::error::GameError> > >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:191
  45: winit::event_loop::EventLoop<tuple$<> >::run<tuple$<>,ggez::event::run::closure_env$0<bunnymark::GameState,enum$<ggez::error::GameError> > >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\event_loop.rs:154
  46: ggez::event::run<bunnymark::GameState,enum$<ggez::error::GameError> >
             at .\src\event.rs:291
  47: bunnymark::main
             at .\examples\bunnymark.rs:186
  48: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,enum$<ggez::error::GameError> >, 0, 20, Err> (*)(),tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\bunnymark.exe` (exit code: 101)

Process finished with exit code 101

```

**Comment by nobbele** [comment]
yeah the buffer size needs to be tweaked, I thought I set it far higher though

**Comment by PSteinhaus** [comment]
And it seems the shadow example shader needs to be adapted (or it's just a typo):

```
C:/Users/jetti/.cargo/bin/cargo.exe run --color=always --package ggez --example shadows
    Finished dev [unoptimized + debuginfo] target(s) in 1.02s
     Running `target\debug\examples\shadows.exe`
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
    
Shader '' parsing error: expected ',', found ';'
  ┌─ wgsl:3:43
  │
3 │     @builtin(position) position: vec4<f32>;
  │                                           ^ expected ','


    expected ',', found ';'

', C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:2391:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: wgpu::backend::direct::default_error_handler
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:2391
   3: core::ops::function::Fn::call<void (*)(enum$<wgpu::Error>),tuple$<enum$<wgpu::Error> > >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:77
   4: alloc::boxed::impl$46::call<tuple$<enum$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler<assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\alloc\src\boxed.rs:1965
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:2377
   6: wgpu::backend::direct::Context::handle_error<enum$<wgpu_core::pipeline::CreateShaderModuleError> >
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:261
   7: wgpu::backend::direct::impl$3::device_create_shader_module
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:1133
   8: wgpu::Device::create_shader_module
             at C:\Users\jetti\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\lib.rs:2005
   9: ggez::graphics::shader::Shader::from_wgsl<ggez::context::Context>
             at .\src\graphics\shader.rs:64
  10: shadows::MainState::new
             at .\examples\shadows.rs:279
  11: shadows::main
             at .\examples\shadows.rs:461
  12: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,enum$<ggez::error::GameError> >, 0, 20, Err> (*)(),tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\shadows.exe` (exit code: 101)

Process finished with exit code 101
```

**Comment by PSteinhaus** [comment]
> yeah the buffer size needs to be tweaked, what should we set it to? 1 million?

To be honest I don't have a feeling for what this number should be right now. I assume your changes (combining groups) led to that buffer being used more, but how exactly? Sorry for being lazy, but you can probably explain it to me faster than I'd research it myself.

**Comment by nobbele** [comment]
its not used more, its just that the default is quite high, I can set it back to the high value again

**Comment by PSteinhaus** [comment]
Then I'm for keeping it high, or at most lowering it a little.

**Pull request merged**
