### PR TITLE
Change graphics getters

### PR DESCRIPTION
**Pull request by beatgammit**
This changes the Drawable and ShaderHandle traits, which is backwards incompatible so I added a note to the Changelog.

I didn't touch top-level pub fns yet because `get_transform` and `transform` do very different things and I didn't know how I should rename them.

Once that's resolved, I can get the rest of the getters done. I *think* the setters are all in the right style, but I could be wrong.

#425

### CODE REVIEW

**Comment by beatgammit** [comment]
Here's what the rest look like in case you want to review them (I *think* this is complete):

```
src/timer.rs
129:pub fn get_delta(ctx: &Context) -> time::Duration {
136:pub fn get_average_delta(ctx: &Context) -> time::Duration {
179:pub fn get_fps(ctx: &Context) -> f64 {
187:pub fn get_time_since_start(ctx: &Context) -> time::Duration {
235:pub fn get_remaining_update_time(ctx: &mut Context) -> time::Duration {
258:pub fn get_ticks(ctx: &Context) -> usize {

src/filesystem.rs
387:pub fn get_user_data_dir(ctx: &Context) -> &path::Path {
392:pub fn get_user_config_dir(ctx: &Context) -> &path::Path {
398:pub fn get_resources_dir(ctx: &Context) -> &path::Path {

src/graphics/mod.rs
583:pub fn get_default_filter(ctx: &Context) -> FilterMode {
591:pub fn get_renderer_info(ctx: &Context) -> GameResult<String> {
605:pub fn get_screen_coordinates(ctx: &Context) -> Rect {
660:pub fn get_projection(context: &Context) -> Matrix4 {
710:pub fn get_transform(context: &Context) -> Matrix4 {
808:pub fn get_window(context: &Context) -> &glutin::Window {
818:pub fn get_size(context: &Context) -> (f64, f64) {
830:pub fn get_hidpi_factor(context: &Context) -> f32 {
836:pub fn get_os_hidpi_factor(context: &Context) -> f32 {
842:pub fn get_drawable_size(context: &Context) -> (f64, f64) {
851:pub fn get_factory(context: &mut Context) -> &mut gfx_device_gl::Factory {
857:pub fn get_device(context: &mut Context) -> &mut gfx_device_gl::Device {
863:pub fn get_encoder(
871:pub fn get_depth_view(
879:pub fn get_screen_render_target(
892:pub fn get_gfx_objects(

src/input/gamepad.rs
33:pub fn get_gamepad(ctx: &Context, id: usize) -> Option<&Gamepad> {
50:pub fn get_axis() {
55:pub fn get_button_pressed() {

src/input/keyboard.rs
244:pub fn get_pressed_keys(ctx: &Context) -> Vec<KeyCode> {
254:pub fn get_active_mods(ctx: &Context) -> KeyMods {

src/input/mouse.rs
60:pub fn get_cursor_type(ctx: &Context) -> MouseCursor {
71:pub fn get_cursor_grabbed(ctx: &Context) -> bool {
84:pub fn get_cursor_hidden(ctx: &Context) -> bool {
97:pub fn get_position(ctx: &Context) -> Point2 {
114:pub fn get_delta(ctx: &Context) -> Point2 {
119:pub fn get_button_pressed(ctx: &Context, button: MouseButton) -> bool {
126:pub fn get_relative_mode() -> bool {```

**Comment by icefoxen** [comment]
`graphics::transform()` has already been renamed to `graphics::transform_projection()` in devel, so you should be good to go.  For setters, I'd be grateful if you could at least take a look at them, especially in various builder structures (conf structs, `ContextBuilder`, `DrawParam` should be the main ones).

**Comment by icefoxen** [comment]
...wait, it hasn't been renamed after all.  The fact that I misread the code is probably a sign of something.    Now fixed.

**Comment by beatgammit** [comment]
Awesome. I'll take a look at the setters as well and see if there's anything that stands out.

**Comment by beatgammit** [comment]
I guess I'll open another PR for the rest of the fixes.

**Pull request merged**
