### PR TITLE
fix context doesn't have a timer field

### PR DESCRIPTION
**Pull request by suryanshmak**
update to use the delta associated function of timer

### CODE REVIEW

**Comment by nobbele** [comment]
I'm not sure I get it. Context has a time field and you should use it over timer::delta

**Comment by suryanshmak** [comment]
it doesn't unless you are talking about another Context type

**Comment by nobbele** [comment]
I think you might have missed the 0.8.0-rc0 update (which master currently points to). See https://www.reddit.com/r/rust_gamedev/comments/v6a3kn/ggez_080rc0_is_out/

**Comment by suryanshmak** [comment]
think i did but the version listed in the docs must be updated from "0.7" to "0.8.0-rc0". i'm just starting out with game dev in rust

**Comment by nobbele** [comment]
0.8.0-rc0 isnt fully released yet so docs dont point to it. To be honest, we could've pushed devel to crates.io and kept master at 0.7 until 0.8 was properly released, I'll keep this in mind next time. Thank you for contributing and pointing this out!

**Comment by suryanshmak** [comment]
also the [https://github.com/ggez/ggez/blob/master/docs/guides/GenerativeArt.md](canvas creation) guide needs to foreshadow that the `from_frame` only works with "0.8.0-rc0".

just read what you replied. sounds good to me!

**Pull request closed without merging**
