### PR TITLE
0.8.0-rc1

### PR DESCRIPTION
**Pull request by nobbele**
Changes from rc0
- Removes HasTwo
- makes `dimensions` take a non-mutable reference
- `logical_size` in WindowMode
- adds support for zip compression
- makes `request_quit` into a context method instead of an event mod function 
- adds missing deprecated functions
- canvas screen coords now equal their size
- export glam
- fix src scaling issue (removes `image_scale` and restores 0.7 behavior)
- updates dependencies
- removes srgb parameter
- bzip2 feature has been renamed to zip-compression
- split text bounds, layout and wrapping
- make `last_delta` and `set_modifiers` public
- move InstanceArray's `ordered` parameter into a separate constructor called `new_ordered`

----------------------

- [x] Note that updating a dep to a breaking version (i.e., nalgebra 0.13 -> 0.14) is a BREAKING API CHANGE and should not be done on things that don't break API. For instance, we screwed this up 'cause ggez 0.4.0 used nalgebra 0.13 and 0.4.1 used nalgebra 0.14... so this broke the exposed API. (Doing this for packages that aren't publically exposed is PROBABLY okay...)
- [x] Fix all rustc warnings
- [x] Make sure all unit tests pass
- [x] Test all examples
- [x] Read all docs (ideally in rendered form)
- [x] Also read (and ideally test) all docs and guides inside the docs folder! (check that links are up to date, etc.)
- [x] rustfmt
- [x] clippy
- [x] Search for and remove all expect() and unwrap() calls
- [x] Search for and address all TODO and BUGGO comments

### CODE REVIEW

**Comment by chamons** [comment]
I hit a regression from devel a few days back that is worth looking at before RC1 goes out - https://github.com/ggez/ggez/issues/1097

**Comment by chamons** [comment]
Sorry to ping on the RC again, but could we consider https://github.com/ggez/ggez/issues/1099 before 0.8.0 goes out? 

There are two APIs that need visibility changes if you want to run your own even loop with keyboard/mouse support.

**Comment by nobbele** [comment]
ok now it should be done, I'll try to publish it tomorrow

**Comment by PSteinhaus** [comment]
The changelog still needs to be updated to reflect some of the changes.
After that we can publish tomorrow :)

**Comment by PSteinhaus** [comment]
Ok, the text example is somewhat broken (one paragraph is way off left). But I hope that’s the last thing to fix and then we can release.

I sadly can’t show you a screenshot right now, but I will, if I remember to, tomorrow morning.

**Comment by chamons** [comment]
@PSteinhaus - I'm not sure it is just a sample issue with text, please see https://github.com/ggez/ggez/issues/1105

**Comment by nobbele** [comment]
ok now everything has to be working

**Review by PSteinhaus — APPROVED** [review]

**Pull request merged**
