### PR TITLE
Move constants to their specific structs

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
This pull request moves...

1. `graphics::WHITE` => `graphics::Color::WHITE`
2. `graphics::BLACK` => `graphics::Color::BLACK`
3. `graphics::DEFAULT_FONT_SCALE` => `graphics::Font::DEFAULT_FONT_SCALE`

### CODE REVIEW

**Comment by icefoxen** [comment]
I like it, but could you please make your changes to the `devel` branch instead of `master`?  :C

**Comment by Andy-Python-Programmer** [comment]
@icefoxen Looks like you already did it. I am not sure if that's it?

**Comment by icefoxen** [comment]
Yeah, and it made ten million merge conflicts.  XD

**Comment by Andy-Python-Programmer** [comment]
@icefoxen Ah I thought you were gonna force push. I will just solve em.

**Comment by Andy-Python-Programmer** [comment]
@icefoxen for some reason I cannot `git pull` and solve the conflicts locally. It normally works. Need to solve them locally as you know the github editor.

**Comment by Andy-Python-Programmer** [comment]
Oh looks like devel is merged into master. Now what /shrug

**Comment by Andy-Python-Programmer** [comment]
I solved the commits using the github editor. Hope it solves them.

**Comment by Andy-Python-Programmer** [comment]
**Note**: The clippy failure is from the master branch and not related to the changes made in this pr.

**Comment by icefoxen** [comment]
Great!  Thank you for all your hard work.

**Comment by Andy-Python-Programmer** [comment]
My pleasure

**Pull request merged**
