### PR TITLE
Add Mandelbrot Exploror to examples, using custom shader 

### PR DESCRIPTION
**Pull request by Ben-PH**
Minor edit to graphics/image.rs to make the compiler happy about imorts. I'm not
so sure on how to make it work without that change :(

If you would prefer this to go into the projects repo, that's cool, but if we can add/make changes to justify putting it into the examples, I'm more than happy for that.

### CODE REVIEW

**Comment by ozkriff** [comment]
> Minor edit to graphics/image.rs to make the compiler happy about imorts. I'm not
so sure on how to make it work without that change :(

What version of rustc are you using?

**Comment by Ben-PH** [comment]
> > Minor edit to graphics/image.rs to make the compiler happy about imorts. I'm not
> > so sure on how to make it work without that change :(
> 
> What version of rustc are you using?

```
$ rustc -V
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by Ben-PH** [comment]
without the change in `graphics/image.rs`, i run `cargo build` inside project root:

```
   Compiling ggez v0.5.0-rc.0 (/home/ben/langs/rust/forks/ggez)
error[E0659]: `image` is ambiguous (name vs any other name during import resolution)
 --> src/graphics/image.rs:5:5
  |
5 | use image;
  |     ^^^^^ ambiguous name
  |
note: `image` could refer to the module imported here
 --> src/graphics/image.rs:12:5
  |
12| use crate::graphics::*;
  |     ^^^^^^^^^^^^^^^^^^
  = help: use `self::image` to refer to this module unambiguously
note: `image` could also refer to the extern crate imported here
 --> src/lib.rs:94:1
  |
94| extern crate image;
  | ^^^^^^^^^^^^^^^^^^^
  = help: use `::image` to refer to this extern crate unambiguously

error: aborting due to previous error

For more information about this error, try `rustc --explain E0659`.
error: Could not compile `ggez`.

```

**Comment by Ben-PH** [comment]
Hold off. Ive realized that this doesnt build on older gpu hardware. Ill make some changes and include some readabiluty updates in the next PR. If you feel i can add/change features to make this a better example, let me know.

**Pull request closed without merging**
