### PR TITLE
Bump lyon to 0.17.5

### PR DESCRIPTION
**Pull request by dchiquito**
Relies on https://github.com/ggez/ggez/pull/917 so that CI succeeds.

* The `basic_shapes` module was removed as described [here](https://github.com/nical/lyon/issues/606), so most of the changes are related to using `FillTesselator` and `StrokeTesselator` instead.
* `BasicVertexConstructor` was also removed, meaning that the only way to add vertices to `BufferedBuilders` is as part of a stroke or fill. The only place where that API was relied on was in `MeshBuilder.triangles`, so I just inserted the vertices directly into the `VertexBuffers`.

### CODE REVIEW

**Comment by dchiquito** [comment]
@icefoxen this should hopefully unblock https://github.com/ggez/ggez/issues/697#issuecomment-777919848.

**Comment by jiyinyiyong** [comment]
quite heavy CPU using a local lib. is there any schedule for finishing this bump?

**Comment by dchiquito** [comment]
@jiyinyiyong The current maintainer is sadly unresponsive, although there is an effort in #875 to transfer ownership of the project. For now I have been using this branch directly as my dependency:
```
[dependencies]
...
ggez = { git = "https://github.com/dchiquito/ggez", branch = "bump-lyon" }
```

**Comment by PSteinhaus** [comment]
I've been using this branch as my dependency without any problems for a while now too. Also people have given only positive feedback to this as far as I can remember, so now that I've looked over the code and everything seems fine I'm just merging it now. It is time.

Bumping lyon and fixing a bit more clippy stuff was necessary and something I think I wouldn't have enjoyed doing myself, so thanks for this PR :)

**Pull request merged**
