### PR TITLE
Break up graphics mod

### PR DESCRIPTION
**Pull request by codingcampbell**
Big fan of this library and the end-goal of reaching LOVE-levels of API happiness. So taking a quick stab of one of the chores at #234

New-ish to Rust here, feel free to throw this PR in the trash if it's doing something terrible. I'm particularly unsure about the `pub(crate)` stuff .. but introducing files made Rust complain a _lot_ about private fields, and `pub(crate)` _seems_ to keep it the same as if everything shared the same file.

### CODE REVIEW

**Comment by icefoxen** [comment]
Wow, thanks a lot!  `pub(crate)` should be just fine.  There might be a slightly simpler way of doing it but if so I don't know what it is.

**Comment by DenialAdams** [comment]
>  There might be a slightly simpler way of doing it but if so I don't know what it is.

Why not an `Image` module?

**Comment by icefoxen** [comment]
Seems like that's what we have now? Not sure what you mean.

**Comment by DenialAdams** [comment]
I meant a new (sub)module but nevermind, I was totally confused and that
wouldn't help at all.

**Pull request merged**
