### PR TITLE
new transform pipeline

### PR DESCRIPTION
**Pull request by termhn**
Possibility for what a new transform pipeline could look like as discussed in #149 and #145. The instance data cannot be sent as a matrix directly, though it would be possible to encode it which I might look into in the future. Currently, I anecdotally see a ~5-10% FPS increase on my desktop when running the spritebatch example vs the current master.

* Only send one combined MVP matrix to GPU
* use nalgebra to generate ortho projection matrix
* store view matrix in a vec with helpers for changing it
* store model matrix in a vec with helpers for changing it
* add helper conversion from DrawParam to matrix

### CODE REVIEW

**Comment by icefoxen** [comment]
I like it. I like it a lot. Need to go through it in more detail, but it looks very nice.

**Comment by icefoxen** [comment]
Aieee, I should have merged this before rewriting and refactoring mesh stuff XD

**Comment by termhn** [comment]
Heh. I'm working on a bit of change to the api to be more like how Love2D does it, but I'm not sure that it's actually that much better than how it is now. Possibly more user friendly? I dunno I'll push a commit here in a bit and you can take a look.

**Comment by icefoxen** [comment]
Okay!  Two questions:

1) Is it ready to merge?  Keeping in mind details can be amended later.
2) Can you rebase it off of current master, given all the refactoring that happened with Mesh?  :/

**Comment by termhn** [comment]
1. Yes, probably, though I have not actually tested some of the functions thoroughly or at all (specifically the new ones I added yesterday.
2. I'll take a look but I don't see why not... this shouldn't have affected that all too much I don't think

**Comment by termhn** [comment]
Alright I'm going to start rebasing this on current master now

**Pull request merged**
