### PR TITLE
Modified the input module somewhat

### PR DESCRIPTION
**Pull request by Ulfr26**
I've added some functions to the keyboard and mouse contexts that can detect whether a button is pressed/released on a certain frame (i.e., pressed this frame but released last frame and vice versa). I also changed the mouse state to be represented with a HashSet, just to keep it consistent with the keyboard.

This requires an extra variable in `KeyboardContext` and `MouseContext` that represents the state of the keyboard/mouse on the previous frame. Alternatively you could represent the state as a `HashMap<KeyCode, (bool, bool)>`, but I don't know if changing this each frame would be more or less efficient than just cloning to a new variable.

### CODE REVIEW

**Comment by PSteinhaus** [comment]
Thank you for this PR!

Glancing over it it looks fine to me. I'll try to take a closer look tomorrow ;)

I'm not 100% sure yet whether this change is really worth it though, as this dynamic kind of information is already kind-of supplied to the user through the EventHandler input callbacks. On the other hand we now have this kind of duplication in many places and I personally like it, as it gives me greater flexibility in how I use the input.

**Comment by nobbele** [comment]
I like this

**Comment by PSteinhaus** [comment]
I like it too.

One small thing that would need to be changed though is that `save_keyboard_state()` and `save_mouse_state()` need to be public, sadly, because we need to give users who are running their own event loop the ability to call them; same situation as with `reset_delta`.
Then, these calls would need to be added to the eventloop example as well, to keep it in sync with our default one.

What I really like is the change from HashMap to HashSet, that's simply better, I think 👍 

I don't really think that going through a `HashMap<KeyCode, (bool, bool)>`, copying each 'current' bool onto the 'previous' one, would be more efficient than just cloning the HashSet, as currently done, but I also hope that the difference wouldn't be too big.

My mind tries to convince me that there has to be some clever buffer-swapping-idea to get around the copying completely, but I guess that'd never work, as both states need to be equal at the start of a frame.

**Comment by Ulfr26** [comment]
No worries, I've made those public now :+1:

**Review by nobbele — APPROVED** [review]

**Pull request merged**
