### PR TITLE
cache source instead of calling Decoder::new() every play

### PR DESCRIPTION
**Pull request by slmjkdbtl**

### CODE REVIEW

**Comment by slmjkdbtl** [comment]
#98

**Comment by slmjkdbtl** [comment]
I'm assuming creating `SamplesBuffer` is cheaper than `Decoder`

**Comment by slmjkdbtl** [comment]
closed because I found that `source.convert_samples().collect::<Vec<f32>>()` is taking 10 seconds even for a small file

**Comment by icefoxen** [comment]
It might be *significantly* faster in release mode than debug mode. But yes.

**Comment by slmjkdbtl** [comment]
@icefoxen what about storing a
```rust
pub struct Source {
    buffer: rodio::source::Buffered,
    // ...
}
impl Source {
    pub fn from_data(context: &mut Context, data: SoundData) -> GameResult<Self> {
        // ...
        let src = Decoder::new(cursor).unwrap();
        Ok(Source {
            buffer: src.buffered(),
            // ...
        })
    }
    // ...
}
```
and play by 
```rust
self.sink.append(self.buffer.clone().convert_samples());
```

I haven't done any benchmarks though

**Pull request closed without merging**
