### PR TITLE
Allow renaming of resources and resources.zip

### PR DESCRIPTION
**Pull request by MatchaChoco010**
Hi!

This is a PR for an additional feature as the title suggests.

I wanted to change the name of `resources.zip` to `data`.
I personally think it's cooler to have `data` with no extension next to the exe than to have a file with a `.zip` extension next to it.
Of course, I understand that hiding the extension does not lead to any kind of encryption.
It's just to make it look cool, nothing more.

I added `resources_dir_name` and `resources_zip_name` as arguments when building the filesystem.
I added a method to ContextBuilder to change this setting.
The default values are set to `resources` and `resources.zip`, which are the same as before, respectively.

As a limitation, unfortunately, this setting cannot be written in `conf.toml`, because `conf.toml` must be in resources, and can only be used after the resources directory has been determined.
Therefore, this setting can only be changed via the `ContextBuilder` method.

I understand that more configuration increases complexity and may threaten "make good games, easily".
However, I believe that adding this setting will not add too much complexity since the default setting is to use the existing `resources` ans `resources.zip`.
If there are any problems, I will withdraw this PR.

Thank you for your patience.
Finally, thanks for the awesome crate!

### CODE REVIEW

**Comment by PSteinhaus** [comment]
Thanks for this PR!

This might be somewhat of a niche feature, but spontaneuosly I don't see any reason to disallow it.

I also don't have a problem with bloating up the ContextBuilder a little to allow for it. It's shortlived enough and since you honored the usual syntax of setting options for it I don't think it increases complexity much. Sure, the documentation becomes a bit longer, but your functions are named pretty self explanatory and the documentation looks nice and short, so why not.

The only thing that confuses me a little are the clippy failures...
Clippy doesn't have any problems with devel, but for some reason it suddenly feels very annoyed about a bunch of stuff you didn't even touch...

**Comment by nobbele** [comment]
maybe remove the change_ prefix?

**Comment by PSteinhaus** [comment]
> maybe remove the change_ prefix?

Right, that's a bit redundant / incoherent with the other method names.

Nobbele was so kind to fix the clippy errors on devel, so if you update your PR to the latest devel version they should be gone here as well.

**Comment by MatchaChoco010** [comment]
OK! I'll merge the latest devel branch and remove the change prefix :+1:

**Review by nobbele — APPROVED** [review]

**Pull request merged**
