### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by chamons**
While taking a look at ggez, I noticed the latest build failed, and it seemed to be mechanical clippy fixes.

I took a few minutes to fix things. Here's what i did::

- Resolved trivial fixes/refactors as tooling suggested, and added clippy allow for others
- Flowing point comparisons touched _many_ tests so silenced with #![allow(clippy::float_cmp)]

Reading the contrib guidelines, it sounds like master is a release branch, so I was uncertain if this should have been done against devel instead? 

Thought if it is a release branch, then maybe it shouldn't have clippy failures? 

Feel free to take what you'd like, or close if this is not helpful.

### CODE REVIEW

**Comment by Elinvynia** [comment]
Seems like the MSRV should be bumped to fix the last appveyor error, as it fails to build on 1.40.0.

**Comment by chamons** [comment]
Looks like they killed it in the dev branch - https://github.com/ggez/ggez/commit/e163452b8fc017a56369d5e69e7b850b895d3a26

So I think it's ignorable?

**Comment by Eosis** [comment]
Hi @chamons , I hope everything is okay with you in Austin!

I also did exactly what you have done here last week, and this is already merged into `devel`. I found I also needed to change the clippy invocation to ignore 3rd party packages (another PR up against GGEZ now), so I am intrigued that this was not necessary for you. 🤔

**Comment by chamons** [comment]
Thanks for asking - thankfully our area was spared the worst of the storm and infrastructure collapse (which is why I was able to hack on fun things like this).

I'm not sure why the difference, I just ran cargo clippy from the command line until it was silent. My machine was Windows, running rust 1.50.

If this is fixed in dev, then feel free to close this then. It'll get picked up in master when you do a merge. :)

**Comment by PSteinhaus** [comment]
I just checked and @Eosis is right. #895 does pretty much the same thing as you did. So I'm a bit sry for just closing this, but thanks for trying :)

**Pull request closed without merging**
