### PR TITLE
Add docs to indicate that primitive draws are inefficient

### PR DESCRIPTION
**Pull request by beatgammit**
The snake example is referenced from a youtube video and a blog post, so
I added documentation there because that's likely one of the first
places a new developer will interact with ggez and base projects on.

I noted in the graphics package that the draws are different from the
love project that it's based on since primitive draw calls seem to be
batched, whereas ggez does *not* do automatic batching. There may be
more places in the source where such notes are useful.

I also added a short note in the README that there may be performance differences between ggez and love. I feel like it would be nice to have a section that details gotchas coming from love. I personally don't have a *ton* of experience with love (or ggez for that matter), but my knee-jerk reaction in #440 was to test on love to see if I was making a fundamental mistake. Having a note in the README about high-level differences from love would be helpful.

### CODE REVIEW

**Comment by icefoxen** [comment]
Nice, thank you!  Though #346 might be interesting to you.

**Comment by termhn** [comment]
out of curiosity @beatgammit which youtube video is the snake example referenced from?

**Comment by beatgammit** [comment]
@termhn I was referring to the [snake example in `piston`](https://m.youtube.com/watch?v=HCwMb0KslX8#) that the snake example for `ggez` was based on. The comments in the source for the example reference it and the github repo.

I don't know if there's a YouTube example for doing this in `ggez`, though I did consider `ggez` because of that example.

**Comment by termhn** [comment]
Nice, okay gotcha. I wrote the snake example after seeing that piston one
but wasn’t sure if someone had made another video that it was included in
:) glad to hear it’s helpful haha

**Pull request merged**
